image: python:3.11

stages:
  - test
  - test_chat_endpoint

run_tests:
  stage: test
  tags:
    - shared
    - docker
    - PoC
    - pilot
  # Use a specific Python image for a predictable runtime
  image: python:3.11
  before_script:
    - python --version
    - pip install --upgrade pip
    # Install backend requirements if the file exists;
    - if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
  script:
    - cd tests
    - python test_prompt_security_result.py

run_chat_endpoint_tests:
  stage: test_chat_endpoint
  tags:
    - shared
    - docker
    - PoC
  image: python:3.11
  before_script:
    - echo "SAIA_API_KEY=$SAIA_API_KEY" >> .env
    - echo "USE_SAIA_API=true" >> .env
    - python --version
    - pip install --upgrade pip
    # Install backend requirements if the file exists;
    - if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
  script:
    - cd tests
    - python test_chat_endpoint.py