image: python:3.11

stages:
  - test_prompt_security
  - test_chat_endpoint_connectivity

run_test_prompt_security:
  stage: test_prompt_security
  tags:
    - dind
    - ude-sse
  # Use a specific Python image for a predictable runtime
  image: python:3.11
  before_script:
    - python --version
    - pip install --upgrade pip
    # Install backend requirements if the file exists;
    - if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
  script:
    - pytest ./tests/test_prompt_security_result.py -v

run_test_chat_endpoint_connectivity:
  stage: test_chat_endpoint_connectivity
  tags:
    - dind
    - ude-sse
  image: python:3.11
  before_script:
    - echo "LANGSMITH_TRACING=true" >> .env
    - echo "LANGSMITH_API_KEY=$LANGSMITH_API_KEY" >> .env
    - echo "LANGSMITH_ENDPOINT=https://eu.api.smith.langchain.com" >> .env
    - echo "SAIA_API_KEY=$SAIA_API_KEY" >> .env
    - echo "USE_SAIA_API=true" >> .env
    - python --version
    - pip install --upgrade pip
    # Install backend requirements if the file exists;
    - if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
  script:
    - pytest ./tests/test_chat_endpoint_connectivity.py -v